version: '3'

tasks:

  build:
    cmds:
      - '{{.DOCKER_COMPOSE_CMD}} -f ./docker/docker-compose.detectors.yaml build'

  download-models:
    cmds:
      - wget https://minio.spindoxlabs.it/rexasipro-public/models/self_supervised_person_detection.zip -P /tmp
      - cd /tmp && unzip -o self_supervised_person_detection.zip
      - sudo cp -r /tmp/self_supervised_person_detection ./data/
      - rm -rf /tmp/self_supervised_person_detection self_supervised_person_detection.zip

  start:
    cmds:
      - '{{.DOCKER_COMPOSE_CMD}} -f ./docker/docker-compose.detectors.yaml up'

  stop:
    cmds:
      - '{{.DOCKER_COMPOSE_CMD}} -f ./docker/docker-compose.detectors.yaml down'
