version: '3'

tasks:

  build-lidar:
    cmds:
      - cmd: docker build -f detectors/lidar/Dockerfile -t rexasi-tracker/lidar-detector .

  build-rgbd:
    cmds:
      - cmd: docker build -f detectors/rgbd/Dockerfile -t rexasi-tracker/rgbd-detector .

  build:
    cmds:
      - task detectors:build-lidar
      - task detectors:build-rgbd

  download-models:
    cmds:
      - wget https://minio.spindoxlabs.it/rexasipro-public/models/self_supervised_person_detection.zip -P /tmp
      - cd /tmp && unzip -o self_supervised_person_detection.zip
      - sudo cp -r /tmp/self_supervised_person_detection ./data/
      - rm -rf /tmp/self_supervised_person_detection self_supervised_person_detection.zip

  start:
    cmds:
      - '{{.DOCKER_COMPOSE_CMD}} -f docker/docker-compose.detectors.yaml up'
