version: '3'

vars:
  BASE_IMAGE_TAG: 'rexasi-tracker/base'

tasks:

  clean:
    cmds:
      - sudo rm -rf build install log resource
      - mkdir -p data
      - sudo chmod -R 777 ./data

  init-network:
    cmds:
      - docker network create rexasi-tracker | true

  build-base-image:
    cmds:
      - docker build -f docker/Dockerfile.base . -t {{.BASE_IMAGE_TAG}}

  build-image:
    cmds:
      - task setup:build-base-image 
      - '{{.DOCKER_COMPOSE_CMD}} -f ./docker/docker-compose.yaml build'

