version: '3'

tasks:

  clean:
    cmds:
      - sudo rm -rf build install log resource
      - mkdir -p data
      - sudo chmod -R 777 ./data

  init-network:
    cmds:
      - docker network create rexasi-tracker | true

  build-image:
    cmds:
      - cmd: docker build -f docker/Dockerfile.arm64 . -t {{.IMAGE_TAG}}
        platforms: [arm64]
      - cmd: docker build -f docker/Dockerfile.amd64 . -t {{.IMAGE_TAG}}
        platforms: [amd64]
