version: '3'

vars:
  BASE_IMAGE_TAG: 'rexasi-tracker/base'

tasks:

  clean:
    cmds:
      - sudo rm -rf build install log resource
      - mkdir -p data
      - sudo chmod -R 777 ./data

  init-network:
    cmds:
      - docker network create rexasi-tracker | true

  build-base-image:
    cmds:
      - cmd: docker build -f docker/Dockerfile.base . -t {{.BASE_IMAGE_TAG}}

  build-image:
    cmds:
      - cmd: task setup:build-base-image 
      - cmd: docker build -f docker/Dockerfile.arm64 . -t {{.IMAGE_TAG}}
        platforms: [arm64]
      - cmd: docker build -f docker/Dockerfile.amd64 . -t {{.IMAGE_TAG}}
        platforms: [amd64]
