version: '3'

tasks:

  clean:
    cmds:
      - sudo rm -rf build install log resource
      - mkdir -p data
      - sudo chmod -R 777 ./data

  init-network:
    cmds:
      - docker network create rexasipro | true

  compile-calibration:
    cmds:
      - docker run -v ./ros:/app {{.IMAGE_TAG}} /bin/bash -c 'cd /app/people_tracker/calibration_code && g++ -Wall -g -std=c++11 -fPIC -shared -c calibration.cpp'
      - docker run -v ./ros:/app {{.IMAGE_TAG}} /bin/bash -c 'cd /app/people_tracker/calibration_code && g++ -shared -o libcalibration.so calibration.o'

  build-image:
    cmds:
      - cmd: docker build -f Dockerfile_gpu.arm64 . -t {{.IMAGE_TAG}}
        platforms: [arm64]
      - cmd: docker build -f Dockerfile_gpu.amd64 . -t {{.IMAGE_TAG}}
        platforms: [amd64]

  download-models:
    cmds:
      - wget https://minio.spindoxlabs.it/rexasipro-public/models/self_supervised_person_detection.zip -P /tmp
      - cd /tmp && unzip -o self_supervised_person_detection.zip
      - sudo cp -r /tmp/self_supervised_person_detection ./data/
      - rm -rf /tmp/self_supervised_person_detection self_supervised_person_detection.zip
