version: "3"

networks:
  rexasipro:
    name: "rexasipro"
    external: true

services:
  rviz:
    image: rexasipro/people-tracker
    command: ros2 run rviz2 rviz2
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rviz:/root/.rviz2/
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    networks:
      - rexasipro

