version: "3"

networks:
  rexasi-tracker:
    name: "rexasi-tracker"
    external: true

services:
  lidar-detector:
    image: rexasi-tracker/lidar-detector
    command: ros2 launch lidar_detector launch.py
    networks:
      - rexasi-tracker
    volumes:
      - ../data:/data
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  rgbd-detector:
    image: rexasi-tracker/rgbd-detector
    command: ros2 launch rgbd_detector launch.py
    networks:
      - rexasi-tracker
    volumes:
      - ../data:/data
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]